spring:
  application:
    name: activity-service

  datasource:
    #  this is for cloud-based PostgreSql neondb
    url: jdbc:postgresql://ep-floral-scene-ahef167u-pooler.c-3.us-east-1.aws.neon.tech/fitness-micro-user?sslmode=require&channel_binding=require'
    username: neondb_owner
    password: npg_wGyh5iEUNt3n

# for mongo db connection
#  data:
#    mongodb:
#      uri: mongodb+srv://amprajapati08893:aman840@cluster0.sguxw.mongodb.net/?appName=Cluster0/aiactivityfitness
#      database: aiactivityfitness

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
#    this instance are vey crucial line as might be rest client whatever u use not detect the other service then use this so it fetch through ip address

kafka:
  topic:
    name: activity-events
server:
  port: 8082