spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-location: file:///C:/Users/pc/Desktop/(AI-Powered Fitness Application) Fitness App with Microservices Arch/config

server:
  port: 8888