spring:
  application:
    name: activity-service
# for mongo db connection
#  data:
#    mongodb:
#      uri: mongodb+srv://amprajapati08893:aman840@cluster0.sguxw.mongodb.net/?appName=Cluster0/aiactivityfitness
#      uri: mongodb://127.0.0.1:27017

  data:
    mongodb:
      uri: mongodb://localhost:27017/activitydb
      database: activitydb

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cloud:
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
#    this instance are vey crucial line as might be rest client whatever u use not detect the other service then use this so it fetch through ip address

kafka:
  topic:
    name: activity-events

server:
  port: 8082