spring:
  datasource:

  #  this is for cloud-based PostgreSql neondb
    url: jdbc:postgresql://ep-floral-scene-ahef167u-pooler.c-3.us-east-1.aws.neon.tech/fitness-micro-user?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_wGyh5iEUNt3n

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: 8081